### ISSUE TITLE
Unable to locate package python3.7-dev

### ISSUE THREAD

**Issue by C-Noob404** [FuocomanSap/P4wnp1-ALOA-Menu-Reworked#4]
First, thank you very much that you did this.
Unfortunately, I got some issues:
E: Unable to locate package python3.7-dev
E: Couldn't find any package by glob 'python3.7-dev'
E: Couldn't find any package by regex 'python3.7-dev'

Maybe you could find the time and look over it?
I would really appreciate it!

Thank you very much!

**Comment by FuocomanSap** [comment]
Have you tried to install python3.7-dev? 

I've just open the console and restarted all but I can't recreate that error.

Try this:

https://www.digitalocean.com/community/questions/unable-to-install-pyhton-3-7-version-on-ubuntu-16-04-error-couldn-t-find-any-package-by-regex-python3-7

And let me know, maybe u just need  "sudo".

**Comment by C-Noob404** [comment]
ok, I worked around it by just setting it to python3, and this is what I got:

`root@kali:~/P4wnp1-ALOA-Menu-Reworked# bash install.sh 
Install Luma.core drivers
Hit:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
588 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dsniff is already the newest version (2.4b1+debian-30).
libfreetype6-dev is already the newest version (2.11.1+dfsg-1).
libjpeg-dev is already the newest version (1:2.1.2-1).
mitmproxy is already the newest version (6.0.2-1).
python3-pip is already the newest version (22.0.2+dfsg-1).
python3.10-dev is already the newest version (3.10.2-1).
The following packages were automatically installed and are no longer required:
  cpp-9 libasan5 libisl22 libmpdec2 libpython2-stdlib libpython2.7 libpython2.7-minimal libpython2.7-stdlib libpython3.7 libpython3.7-minimal libpython3.7-stdlib
  python-all python-certifi python-cffi-backend python-crypto python-keyrings.alt python-lxml python-pip-whl python-pkg-resources python-setuptools python-six
  python-wheel python-xdg python2 python2-minimal python2.7 python2.7-minimal python3-asn1crypto python3.7-minimal
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 588 not upgraded.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting luma.oled
  Using cached luma.oled-3.8.1-py2.py3-none-any.whl (32 kB)
Collecting luma.core>=2.0.0
  Using cached luma.core-2.3.1-py2.py3-none-any.whl (71 kB)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.9/dist-packages (from luma.core>=2.0.0->luma.oled) (0.4.1)
Collecting pillow>=4.0.0
  Using cached Pillow-9.0.1.tar.gz (49.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyftdi in /usr/local/lib/python3.9/dist-packages (from luma.core>=2.0.0->luma.oled) (0.53.3)
Requirement already satisfied: deprecated in /usr/local/lib/python3.9/dist-packages (from luma.core>=2.0.0->luma.oled) (1.2.13)
Requirement already satisfied: cbor2 in /usr/local/lib/python3.9/dist-packages (from luma.core>=2.0.0->luma.oled) (5.4.2.post1)
Requirement already satisfied: RPI.GPIO in /usr/local/lib/python3.9/dist-packages (from luma.core>=2.0.0->luma.oled) (0.7.1)
Collecting spidev
  Using cached spidev-3.5.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.9/dist-packages (from deprecated->luma.core>=2.0.0->luma.oled) (1.13.3)
Requirement already satisfied: pyusb!=1.2.0,>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from pyftdi->luma.core>=2.0.0->luma.oled) (1.2.1)
Requirement already satisfied: pyserial>=3.0 in /usr/local/lib/python3.9/dist-packages (from pyftdi->luma.core>=2.0.0->luma.oled) (3.5)
Building wheels for collected packages: pillow, spidev
  Building wheel for pillow (setup.py) ... done
  Created wheel for pillow: filename=Pillow-9.0.1-cp39-cp39-linux_armv6l.whl size=1044237 sha256=5907c6206bb3f25d702bc2edacefd57b64ae39b05f66f04d8c25dfdc8b7d7e7a
  Stored in directory: /root/.cache/pip/wheels/0a/57/42/9db4ad84e58e183cd12ef4f5fda609a756f0fb6cdc648f8f9e
  Building wheel for spidev (setup.py) ... done
  Created wheel for spidev: filename=spidev-3.5-cp39-cp39-linux_armv6l.whl size=39352 sha256=cfcd98f16272a8e16090f0c0378b20a752055f9b81e316c9e26f45dc8d00ec3b
  Stored in directory: /root/.cache/pip/wheels/af/4b/86/7f9af5f0c9fbcca1aa3279380b64bf55f323ba022485d9a041
Successfully built pillow spidev
Installing collected packages: spidev, pillow, luma.core, luma.oled
Successfully installed luma.core-2.3.1 luma.oled-3.8.1 pillow-9.0.1 spidev-3.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: luma.core in /usr/local/lib/python3.9/dist-packages (2.3.1)
Requirement already satisfied: deprecated in /usr/local/lib/python3.9/dist-packages (from luma.core) (1.2.13)
Requirement already satisfied: RPI.GPIO in /usr/local/lib/python3.9/dist-packages (from luma.core) (0.7.1)
Requirement already satisfied: pillow>=4.0.0 in /usr/local/lib/python3.9/dist-packages (from luma.core) (9.0.1)
Requirement already satisfied: pyftdi in /usr/local/lib/python3.9/dist-packages (from luma.core) (0.53.3)
Requirement already satisfied: spidev in /usr/local/lib/python3.9/dist-packages (from luma.core) (3.5)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.9/dist-packages (from luma.core) (0.4.1)
Requirement already satisfied: cbor2 in /usr/local/lib/python3.9/dist-packages (from luma.core) (5.4.2.post1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.9/dist-packages (from deprecated->luma.core) (1.13.3)
Requirement already satisfied: pyserial>=3.0 in /usr/local/lib/python3.9/dist-packages (from pyftdi->luma.core) (3.5)
Requirement already satisfied: pyusb!=1.2.0,>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from pyftdi->luma.core) (1.2.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Create directories
Copying files
Copying run script in local P4wnP1 script
All files are ready
to run with P4wnP1 boot
Go thru web interface
Go in trigger section
Create new trigger
on service start :
run script sh and choose 
runmenu.sh
Enjoy
by default gui.py use SPI interface
if you use I2C oled edit gui.py
and set I2C_USER = 1`

Looks alright, but it doesn't work.
It also can't build the wheel for Pillow.  ERROR: Failed building wheel for Pillow

**Comment by C-Noob404** [comment]
Ok, I've found the problem:

` no pid
Traceback (most recent call last):
  File "/root/BeBoXGui/gui.py", line 8, in <module>
    import RPi.GPIO as GPIO
  File "/usr/local/lib/python3.9/dist-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
ModuleNotFoundError: No module named 'RPi._GPIO'`

But I must admit, I have no Idea what to do^^
